targets:
  - 
    x: 100
    y: 100
  - 
    x: 200
    y: 100
  - 
    x: 300
    y: 100
  - 
    x: 400
    y: 100
  - 
    x: 500
    y: 100
  - 
    x: 600
    y: 100
  - 
    x: 700
    y: 100
  - 
    x: 100
    y: 200
  - 
    x: 200
    y: 200
  - 
    x: 300
    y: 200
  - 
    x: 400
    y: 200
  - 
    x: 500
    y: 200
  - 
    x: 600
    y: 200
  - 
    x: 700
    y: 200